# Define your admin routes here

app_events:
    type: rest
    resource: App\Controller\Admin\EventController
    prefix: /admin/api
    name_prefix: app.
    options:
        expose: true

app_event_registrationss:
    type: rest
    resource: App\Controller\Admin\EventRegistrationController
    prefix: /admin/api
    name_prefix: app.
    options:
        expose: true
